// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package dbproducts

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	DeleteProduct(ctx context.Context, id int32) error
	GetProduct(ctx context.Context, id int32) (Product, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
